name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "Break Changes"
    labels: "break-change"
  - title: "Features"
    labels: "feature"
  - title: "Bug Fixes"
    labels: "bug"
  - title: "Documentation"
    label: "documentation"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: minor
template: |
  ## Changes

  $CHANGES
