name: Update pull request label

on:
  pull_request:
    types: [opened]

jobs:
  pull-request-pr-labeler:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/config/pr-labeler.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
