name: Auto Assign

on:
  pull_request:
    types: [opened, reopened]

jobs:
  pull-request-auto-assignee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-add-assignees@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          assignees: ${{ github.actor }}
